version: "3.9"

services:
  frontend:
    image: alaminislam34/casezy:latest
    container_name: casezy
    ports:
      - "3000:3000"
    restart: always
    
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_WS_BASE_URL=${NEXT_PUBLIC_WS_BASE_URL}
    
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 600M
        reservations:
          cpus: "0.3"
          memory: 300M
    
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: lexi-ai-network
    driver: bridge